version: '3.4'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    #image: nginx
    ports:
      - "80:80" #change for VM
    #depends_on:
    restart: always
