version: '3.4'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "8080:443" #change for VM
    networks:
      - inception
    #volumes:            #ADD VOLUME
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    networks:
      - inception
    #volumes:            #ADD VOLUME
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    networks:
      - inception
    #volumes:          #ADD VOLUME
    restart: on-failure

networks:
    inception:
        driver: bridge
