version: '3.4'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443" #change for VM
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cdapurif/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/cdapurif/data/mariadb'
